const Languages = {
    board: {
        title1: 'Đầu tư an toàn cùng Tienngay.vn',
        txt1: 'TienNgay.vn có giấy phép kinh doanh và hoạt động theo quy định của pháp luật và đồng nhất trên toàn hệ thống. Số tiền lãi được trả đúng hạn theo cam kết, giải quyết thắc mắc (nếu có) tận tình, nhanh chóng',
        title2: 'Lãi suất hấp dẫn cùng Tienngay ',
        txt2: 'Tham gia gửi tiền có kỳ hạn Online tại Tienngay để có thêm thời gian tận hưởng cuộc sống và luôn an tâm rằng tiền của bạn đang sinh lời với lãi suất hấp dẫn.',
        title3: 'Rõ ràng - Minh bạch',
        txt3: 'Tất cả các thao tác của Nhà đầu tư được ghi lại bằng hệ thống của TienNgay.vn, đảm bảo số tiền lãi nhận về rõ ràng, minh bạch.'
    },
    transaction: {
        title: 'Lịch sử giao dịch',
        debtNow: 'Số dư hiện có',
        all: 'Tất cả',
        inMoney: 'Tiền vào',
        outMoney: 'Tiền ra',
        transaction: 'Giao dịch',
        fromDate: 'Từ ngày',
        toDate: 'Tới ngày',
        allInvestNow: 'Tổng đầu tư hiện tại',
        noDataTransaction: 'Bạn chưa thực hiện giao dịch nào!'
    },
    home: {
        title: 'Trang chủ',
        sumInvest: 'Tổng vốn đầu tư',
        sumpProfit: 'Tổng lãi đã nhận',
        sumResidualProfit: 'Tổng lãi còn lại',
        totalCaption: 'Tổng vốn còn lại',
        balanceVimo: 'Số dư ví Vimo',
        have: 'Đang có',
        vnd: ' VNĐ',
        invest: 'Đầu tư',
        report: 'Báo cáo',
        payment: 'Thanh toán',
        investPackages: 'Các gói đầu tư nổi bật',
        investNow: 'Đầu tư ngay',
        more: 'Xem thêm',
        stockVfs: 'Chứng khoán VFS',
        question: 'Câu hỏi thường gặp',
        signFree: 'Đăng ký mở tài khoản miễn phí',
        todoInvest: 'Làm thế nào để đầu tư vào Tienngay.vn?',
        todoWithDrawMoney: 'Làm thế nào để rút tiền từ Tienngay.vn?',
        percentCalculated: 'Phần trăm lãi đầu tư được tính như thế nào?',
        paymentMethod: 'Hình thức trả tiền như thế nào?',
        interestRateMonth: 'Lãi xuất tháng',
        timeInvest: 'Thời gian đầu tư',
        interestExpected: 'Lãi dự kiến',
        formInterestPay: 'Hình thức trả lãi',
        hello: 'Chào mừng bạn đến với',
        nameApp: 'TienNgay.Vn',
        investAndAccumulate: 'Đầu tư & Tích luỹ',
        newMedia: 'Tin tức truyền thông',
        investNowFloral: 'ĐẦU TƯ NGAY',
        noNotify: 'Bạn không có thông báo nào'

    },
    invest: {
        title: 'Đầu tư',
        investing: 'Đang đầu tư',
        history: 'Đã đáo hạn',
        enter: 'Nhập số tiền mà bạn muốn tìm kiếm',
        time: 'Thời gian đầu tư',
        formalPayment: 'Hình thức trả lại',
        investNow: 'Đầu tư ngay',
        interest: 'Lãi suất tháng',
        attractInvest: 'Đầu tư hấp dẫn',
        intent: 'Lãi dự kiến',
        getMoney: 'Lãi đã nhận',
        sumMoney: 'Tổng tiền đã nhận',
        monthInvest: 'Thời gian đầu tư',
        chooseMoney: 'Số tiền đầu tư',
        packageInvest: 'Tìm kiếm gói đầu tư',
        search: 'Tìm kiếm',
        cancel: 'Hủy',
        notify: 'Thông báo',
        notifyAll: 'Tất cả',
        notifyUnRead: 'Chưa đọc',
        customerGratitude: 'Tri ân khách hàng cùng tienngay.vn',
        investPay: 'Trả lãi đầu tư',
        investSuccess: 'Đầu tư thành công',
        changePercent: 'Thay đổi tích luỹ phần trăm',
        availableBalance: 'Số dư hiện có',
        policy: 'Điều khoản sử dụng và chính sách',
        updateBankInfo:
            'Bạn chưa cập nhật hình thức nhận tiền lãi đầu tư. Bạn có muốn cập nhật ngay bây giờ không?',
        payFinished:
        '<a>Giao dịch đã hoàn thành, bạn vui lòng xem chi tiết trong lịch sử thanh toán</a>',
        error:'Không lấy được dữ liệu',
        emptyData1: 'Không có gói đầu tư nào phù hợp.',
        emptyData2: 'Bạn chưa có gói đầu tư nào, cùng đầu tư ngay nào !!!',
        fromDate:'Từ ngày',
        toDate:'Đến ngày'
    },
    account: {
        title: 'Tài khoản',
        payMethod: 'Hình thức nhận tiền',
        linkWallet: 'Liên kết ví điện tử',
        changePwd: 'Đổi mật khẩu',
        loginWithFinger: 'Xác thực nhanh vân tay',
        loginWithFaceId: 'Xác thực nhanh Face ID',
        accountLink: 'Tài khoản liên kết',
        policy: 'Điều kiện và điều khoản',
        shareFriends: 'Mời bạn bè',
        web: 'TienNgay.vn trên website',
        facebook: 'TienNgay.vn trên Facebook',
        useManual: 'Hướng dẫn sử dụng',
        answer: 'Hỏi đáp',
        hotline: 'Hotline',
        rate: 'Đánh giá cho TienNgay.vn',
        accVerified: 'Tài khoản đã xác thực',
        accuracyNow: 'Xác thực ngay',
        logout: 'Đăng xuất',
        waitVerify: 'Tài khoản đang chờ xác thực',
        logoutNotice: 'Bạn có chắc chắn muốn đăng xuất không?'

    },
    report: {
        title: 'Báo cáo',
        quarterlyOverview: 'Tổng quan theo quý',
        financialChart: 'Biểu đồ tài chính',
        month: 'Tháng',
        investment: 'Vốn đầu tư',
        moneyCollected: 'Tiền thu về',
        overview: 'Tổng quan',
        quarter: 'Quý',
        year: 'Năm',
        monthOfQuarter: 'Chi tiết tháng trong quý',
        contractNumber: 'Số hợp đồng',
        investMoney: 'Số tiền đầu tư',
        originMoneyCollected: 'Số tiền gốc thu về',
        interest: 'Tiền lãi'
    },
    common: {
        search: 'Tìm kiếm',
        agree: 'Đồng ý',
        cancel: 'Hủy',
        continue: 'Tiếp tục',
        vnd: 'VNĐ',
        million: '(Triệu)',
        hotline: '18006907',
        notice: 'Thông báo',
        rate: 'Đánh giá',
        yourRate: 'Đánh giá của bạn',
        comment: 'Nội dung đánh giá',
        descriptionRating: 'Chúng tôi rất hi vọng nhận được đánh giá từ bạn nhằm nâng cao chất lượng phục vụ.',
        thanksRating: 'Cám ơn bạn đã đóng góp ý kiến !',
        send: 'Gửi'
    },
    introduce: {
        txtIntroduce1: 'Đầu tư an toàn cùng Tienngay',
        txtIntroduce2: 'TienNgay.vn có giấy phép kinh doanh và hoạt động theo quy định của pháp luật và đồng nhất trên toàn hệ thống. Số tiền lãi được trả đúng hạn theo cam kết, giải quyết thắc mắc (nếu có) tận tình, nhanh chóng',
        txtContinue: 'Tiếp tục',
        txtIntroduce3: 'Lãi suất hấp dẫn cùng Tienngay',
        txtIntroduce4: 'Tham gia gửi tiền có kỳ hạn Online tại Tienngay để có thêm thời gian tận hưởng cuộc sống và luôn an tâm rằng tiền của bạn đang sinh lời với lãi suất hấp dẫn.',
        introduce5: 'Rõ ràng - Minh bạch',
        introduce6: 'Tất cả các thao tác của Nhà đầu tư được ghi lại bằng hệ thống của TienNgay.vn, đảm bảo số tiền lãi nhận về rõ ràng, minh bạch.'
    },
    auth: {
        txtPhone: 'Số điện thoại',
        txtPass: 'Mật khẩu',
        txtLogin: 'Đăng nhập',
        txtLoginWith: 'Đăng nhập với',
        txtSignUp: 'Đăng ký',
        txtName: 'Họ và tên',
        txtEmail: 'Email',
        txtConfirmPass: 'Xác nhận mật khẩu',
        knowChannel: 'Bạn biết chúng tôi qua kênh nào ?',
        txtTitleOtp: 'Xác nhận OTP',
        txtConfirmOtp: 'Nhập mã OTP đã được gửi về điện thoại bạn đã xác nhận',
        conFirm: 'Xác nhận',
        saveAcc: 'Lưu tài khoản',
        forgotPwd: 'Quên mật khẩu',
        txtD: 'Đăng',
        txtK: 'ký',
        titleForgotPass: 'Xác minh số điện thoại',
        txtForgotPass: 'Nhập số điện thoại đã được liên kết với tài khoản của bạn',
        accuracy: 'Xác thực',
        sentOTP: 'Gửi mã',
        txtConfirmNewPass: 'Nhập lại mật khẩu mới',
        txtNewPass: 'Mật khẩu mới',
        titleChangePass: 'Thay đổi mật khẩu',
        txtChange: 'Thay đổi mật khẩu của bạn và đăng nhập lại',
        change: 'Thay đổi',
        succuss: 'Đăng ký thành công',
        notifySuccess: 'Chúc mừng bạn đã đăng ký thành công TienNgay.vn Đầu tư & Tích luỹ. Tiến hành đầu tư ngay và nhận lãi khủng hàng tháng',
        continue: 'Tiếp tục',
        successChangePass: 'Đổi mật khẩu thành công !'
    },
    errorMsg: {
        userNameRequired: 'Họ và tên không được để trống',
        userNameLength: 'Họ và tên không được ít hơn 8 ký tự',
        userNameRegex: 'Họ và tên không được chứa ký tự đặc biệt hoặc số',
        emailNull: 'Email không được để trống',
        emailRegex: 'Email không đúng định dạng',
        cardNull: 'Số CMND/CCCD không được để trống',
        cardRegex: 'Số CMND/CCCD phải là số',
        cardCheck: 'Số CMND/CCCD không hợp lệ',
        pwdNull: 'Mật khẩu không được để trống',
        pwdCheck: 'Mật khẩu không được ít hơn 8 ký tự',
        conFirmPwd: 'Xác nhận mật khẩu không trùng khớp với mật khẩu',
        phoneIsEmpty: 'Số điện thoại không được để trống',
        phoneRegex: 'Số điện thoại không đúng định dạng',
        phoneCount: 'Số điện thoại chỉ được 10 số',
        genderRequired: 'Giới tính không được để trống',
        addressNull: 'Địa chỉ không được để trống',
        addressRegex: 'Địa chỉ không được chứa kí tự đặc biệt',
        jobNull: 'Nghề nghiệp không được để trống',
        jobRegex: 'Nghề nghiệp không được chứa kí tự đặc biệt',
        birthdayNull: 'Ngày sinh không được để trống',
        birthdayRegex: 'Ngày sinh không đúng định dạng (vd: 05/11/1999)',
        birthdayCompare18: 'Chưa đủ 18 tuổi',
        errStk: 'Số tài khoản hoặc số thẻ vượt quá giới hạn cho phép',
        errStkEmpty: 'Số tài khoản hoặc số thẻ trống',
        errNameEmpty: 'Tên chủ tài khoản ngân hàng trống',
        errBankEmpty: 'Ngân hàng chưa được chọn',
        noInternet: 'Kết nối bị gián đoạn, vui lòng thử lại!',
        sessionExpired: 'Kết nối bị gián đoạn, vui lòng thử lại!',
        errEmptyIdentity: 'Bạn cần điền đầy đủ thông tin trước khi xác thực'
    },
    quickAuThen: {
        title: 'Mật khẩu và đăng nhập',
        quickButton: 'Sử dụng xác thực nhanh',
        fingerAuThen: 'Bảo mật vân tay',
        faceid: 'Nhận diện khuôn mặt',
        pin: 'Mã Pin',
        changePwd: 'Chỉnh sửa mật khẩu',
        confirm: 'Xác thực của bạn',
        useFaceId: 'Đăng nhập nhanh bằng Face ID',
        useTouchId: 'Đăng nhập nhanh bằng vân tay',
        facIdConFirm:
            'Quý khách có muốn sử dụng Face ID làm phương thức xác thực chính',
        touchIdConfirm:
            'Quý khách có muốn sử dụng vân tay làm phương thức xác thực chính',
        passcodeConfirm:
            'Quý khách có muốn sử dụng mã pin làm phương thức xác thực chính',
        description: 'Đăng nhập bằng vân tay của bạn',
        useFaceID: 'Sử dụng Face ID để đăng nhập vào Univest',
        useTouchID: 'Sử dụng Touch ID để đăng nhập vào Univest',

        goToSetting: 'Cài đặt',
        desSetPasscode: 'Vui lòng thêm mã PIN để cài đặt xác thực nhanh',
        desSetTouchId: 'Vui lòng thêm vân tay để xác thực nhanh',
        desSetFaceId: 'Vui lòng thêm Face ID để xác thực nhanh',
        successAddTouchId: 'Đã thêm vân tay vào xác thực nhanh của bạn',
        successAddFaceId: 'Đã thêm Face ID vào xác thực của bạn',
        quickAuthn: 'Xác thực nhanh của bạn'
    },
    setPassCode: {
        titleEnter: 'Xác thực mã PIN',
        titleSetPasscode: 'Sử dụng mã PIN để xác thực nhanh',
        repeat: 'Nhập lại mã PIN',
        errorSet: 'Mã PIN trước và mã PIN sau không trùng khớp',
        errorEnter: 'Mã PIN không đúng',
        footerText: 'Tiếp tục'
    },
    errorBiometryType: {
        NOT_DEFINE: 'Vui lòng thêm ít nhất 1 vân tay vào thiết bị của bạn',
        // ios
        RCTTouchIDNotSupported: 'Không hỗ trợ xác thực vân tay trên thiết bị này',
        RCTTouchIDUnknownError:
            'Đăng nhập thất bại nhiều lần, vui lòng đăng nhập với mật khẩu',
        LAErrorTouchIDNotEnrolled:
            'Vui lòng thêm ít nhất 1 faceId vào thiết bị của bạn',
        LAErrorTouchIDNotAvailable:
            'Không có sẵn xác thực nhanh trên thiết bị của bạn',
        ErrorFaceId: 'Vui lòng thêm ít nhất 1 xác thực faceId vào thiết bị của bạn',
        // android
        NOT_SUPPORTED: 'Không hỗ trợ xác thực vân tay trên thiết bị này',
        NOT_AVAILABLE: 'Không hỗ trợ xác thực vân tay trên thiết bị này',
        NOT_ENROLLED: 'Vui lòng thêm ít nhất 1 vân tay vào thiết bị của bạn',
        FINGERPRINT_ERROR_LOCKOUT_PERMANENT:
            'Xác thực không thành công, thử lại sau',
        LAErrorTouchIDLockout:
            'Đã xảy ra lỗi do đăng nhập quá nhiều lần, vui lòng thử lại sau'
    },
    accountInfo: {
        accountInfo: 'Thông tin cá nhân',
        content: 'Xác thực tài khoản để tăng độ an toàn khi đầu tư và sử dụng ứng dụng',
        noteWaitVerify: 'Tài khoản của bạn đang được xác thực, bạn có thể đầu tư ngay sau khi chứng từ được xác thực',
        accWaitVerify: 'Tài khoản đang được xác thực',
        phoneNumber: 'Số điện thoại',
        gender: 'Giới tính',
        fullName: 'Họ và tên',
        birthday: 'Ngày sinh',
        email: 'Email',
        job: 'Nghề nghiệp',
        address: 'Địa chỉ',
        edit: 'Chỉnh sửa',
        save: 'Lưu lại',
        editAcc: 'Chỉnh sửa thông tin',
        successEdit: 'Chỉnh sửa thông tin thành công',
        chooseAvatarUser: 'Chọn hình đại diện ứng dụng'
    },
    accountIdentify: {
        accountIdentify: 'Xác thực tài khoản',
        KYC: 'Số CMND/CCCD',
        imageIdentify: 'Ảnh giấy tờ tùy thân',
        frontKYC: 'Mặt trước CMND',
        behindKYC: 'Mặt sau CMND',
        avatarPhoto: 'Ảnh chân dung chụp:',
        note: '<p><r>Chú ý:</r><s> Hãy xác thực chính xác thông tin của bạn để bắt đầu đầu tư. Sau khi tài khoản bạn được xác thực thành công, bạn không thể thực hiện xác thực lại.</s></p>',
        avatar: 'Chân dung khuôn mặt',
        confirmKYC: 'Xác thực giấy tờ',
        noteTopIdentify: '<p><r>Chú ý:</r><s> Tài khoản của bạn đã được xác thực thành công, bạn không thể thực hiện xác thực lại.</s>',
        waitVerify: 'Chờ xác minh chứng từ',
        waitVerifyContent: 'Chứng từ của bạn đang được xác minh, bạn có thể tiến hành đầu tư sau khi chứng từ đã được xác thực'
    },
    otp: {
        keyOtp: 'Xác nhận ',
        confirmOtp: 'Hãy nhập và xác nhận mã OTP',
        verificationCode: 'Mã xác thực đã được gửi đến số điện thoại ',
        codeExpiresLater: ' Mã hết hiệu lực sau ',
        resentCode: 'Gửi lại mã',
        popupOtpErrorTitle: 'Thông báo OTP',
        popupOtpErrorDescription: 'OTP không chính xác',
        popupOtpSuccessDescription: 'Đăng ký thành công',
        popupOtpResendCode: 'Mã OTP đã hết hạn. Vui lòng gửi lại',
        sentOtp1: 'Gửi lại mã sau: ',
        sentOtp2: 'Gửi lại mã',
        title: 'Xác thực OTP',
        completionOtp: 'Hãy xác nhận mã OTP của chúng tôi đã gửi cho bạn để hoàn thành đầu tư',
        otp1: 'otp1',
        otp2: 'otp2',
        otp3: 'otp3',
        otp4: 'otp4',
        otp5: 'otp5',
        otp6: 'otp6'
    },
    location: {
        PermissionAlert: 'PermissionAlert',
        AccessLocationServices: 'AccessLocationServices',
        OpenSetting: 'OpenSetting',
        Cancel: 'Cancel'
    },
    image: {
        camera: 'Camera',
        library: 'Thư viện ảnh',
        permissionAlert: 'Yêu cầu truy cập',
        accessPhotoMsg: 'Investor cần truy cập vào thư viện ảnh của bạn',
        accessCameraMsg: 'Investor cần truy cập vào camera của bạn',
        accessAddPhotoMsg: 'Investor cần thêm ảnh vào thư viện ảnh của bạn',
        openSetting: 'Mở cài đặt',
        deny: 'Từ chối',
        uploading: 'Đang tải ảnh',
        singleUploading: 'Đang tải ảnh lên',
        selectedThumb: 'Đã chọn hình đại diện',
        selectAsThumb: 'Đặt làm hình đại diện',
        uploadFailed: 'Xảy ra lỗi trong quá trình tải ảnh lên'
    },
    shareFriend: {
        introduce: 'Giới thiệu',
        introduceContent: '<t><c>Giới thiệu thêm nhà đầu tư để có cơ hội nhận những phần quà lên tới 40 triệu đồng tới từ</c> <g>TienNgay.vn</g><c> Đầu tư & Tích luỹ</c></t>',
        introduceCode: 'Mã giới thiệu của bạn',
        qrCode: 'Qr code tải app'
    },
    detailInvest: {
        title: 'Chi tiết khoản đầu tư',
        information: 'Thông tin hợp đồng',
        idContract: 'Mã số hợp đồng',
        interest: 'Lãi suất hàng tháng',
        amountInterest: 'Tổng lãi nhận được',
        period: 'Kỳ hạn đầu tư',
        day: 'Ngày đầu tư',
        formality: 'Hình thức trả lãi',
        investNow: 'Đầu tư ngay',
        inforInterest: 'Thông tin trả lãi',
        amountMoney: 'Tổng số tiền đầu tư',
        moneyInvest: 'Số tiền đầu tư',
        amountReceived: 'Tổng lãi đã nhận',
        expectedDate: 'Ngày đáo hạn dự kiến',
        reinvest: 'Đầu tư lại',
        interestMonth: 'Lãi hàng tháng',
        money: 'Số tiền cần đầu tư',
        method: 'Phương thức đầu tư',
        vimo: 'Tài khoản Vimo',
        nganLuong: 'Tài khoản Ngân Lượng',
        linked: 'Đã liên kết',
        paid: 'Đã thanh toán',
        unpaid: 'Chưa thanh toán',
        agreeTermsWith: 'Tôi đã đọc và đồng ý với ',
        rules: 'Điều khoản sử dụng và chính sách ',
        tienngay: 'của Tienngay.vn',
        error:'Không lấy được dữ liệu, vui lòng thử lại sau',
        notLinked:'Chưa liên kết'
    },
    changePwd: {
        title: 'Đổi mật khẩu',
        titleUpdatePwd: 'Cập nhật mật khẩu',
        oldPass: 'Mật khẩu cũ',
        newPass: 'Mật khẩu mới',
        confirmPwd: 'Đổi mật khẩu',
        currentNewPass: 'Xác nhận mật khẩu mới',
        placeOldPass: 'Nhập mật khẩu cũ',
        placeNewPass: 'Xác nhận mật khẩu mới',
        button: 'Xác nhận đổi mật khẩu',
        notifyContent: 'Xác nhận đổi mật khẩu',
        notify: 'Thông báo',
        successNotify: 'Xác nhận đổi mật khẩu thành công'
    },
    linkSocialAcc: {
        linked: 'Đã liên kết',
        notLinked: 'Chưa liên kết',
        link: 'Liên kết ',
        titleSocial: 'Liên kết tài khoản',
        apple: 'Apple Store',
        fb: 'Facebook',
        google: 'Google',
        notification: 'Thông báo',
        desciption: 'Vui lòng liên kết tài khoản mạng xã hội'
    },
    paymentMethod: {
        methodChoose: 'Chọn phương thức nhận lãi của bạn',
        vimo: 'Tài khoản Vimo',
        bank: 'Tài khoản Ngân hàng',
        cancelLinkVimo: 'Huỷ liên kết ví Vimo',
        changeMethodBank: 'Bạn có muốn chuyển sang liên kết ngân hàng',
        changeMethodVimo: 'Bạn có muốn chuyển sang liên kết Vimo',
        contentCancelLinkVimo: 'Bạn có thật sự muốn huỷ liên kết với ví Vimo. Nếu bạn huỷ liên kết bạn sẽ không thể đầu tư bằng ví Vimo',
        onPressToLink: 'Chạm để liên kết ví',
        onPressToCancelLink:'Chạm để hủy liên kết ví'
    },
    accountBank: {
        bankChoose: 'Chọn ngân hàng',
        accountNumber: 'Số tài khoản',
        ATMNumber: 'Số thẻ ATM',
        inputAccountNumber: 'Nhập số tài khoản',
        accountProvider: 'Chủ tài khoản',
        accountProviderName: 'Tên chủ tài khoản',
        noteAccountBank: '<p><r>Chú ý:</r> <s>Đây là tài khoản ngân hàng để nhận lãi, bạn cần đảm bảo chính xác thông tin tài khoản ngân hàng bạn cung cấp là chính xác.</s> <g>TienNgay.vn</g><s> sẽ không chịu trách nghiệm khi bạn nhập sai thông tin.</s></p>',
        addAccount: 'Thêm tài khoản'
    },
    confirmPhone: {
        confirmPhone: 'Xác nhận số điện thoại',
        noteConfirmPhone: '<p><r>Chú ý:</r> <s>Hãy sử dụng số điện thoại đã đăng ký tài khoản Vimo của bạn để nhận mã OTP</s></p>',
        phone: 'Số điện thoại',
        inputPhone: 'Nhập số điện thoại',
        sendOTP: 'Gửi OTP',
        reSendOTP: 'Gửi lại mã OTP',
        verifyOTP: 'Xác nhận OTP',
        noteVerifyOTP: '<p><r>Chú ý:</r> <s> Mã OTP đã được gửi về số điện thoại %phone, nhập mã OTP và xác nhận để liên kết tài khoản</s></p>',
        reSendCode: 'Gửi lại mã sau ',
        sendAgain: 'Gửi lại mã',
        sendAgainTime: 'sau',
        popupOtpResendCode: 'Mã OTP đã hết hạn. Vui lòng gửi lại',
        popupOtpErrorTitle: 'Thông báo OTP',
        popupOtpErrorDescription: 'OTP không chính xác'
    },
    msgNotify: {
        successCancelLinkVimo: 'Bạn đã hủy liên kết với Vimo',
        failCancelLinkVimo: 'Hủy liên kết với Vimo thất bại',
        successSendLinkVimo: 'Investor đang gửi mã OTP',
        failSendLinkVimo: 'Số điện thoại này không phải là số liên kết với Vimo',
        successAccountLinkBank: 'Liên kết thành công tài khoản ngân hàng',
        failAccountLinkBank: 'Liên kết thất bại tài khoản ngân hàng',
        failVerifyOTP: 'Mã xác thực OTP không đúng',
        successLinkWithVimo: 'Liên kết thành công với Vimo',
        failPostIdentity: 'Lỗi gửi ảnh',
        successVimoLink: 'Liên kết Vimo thành công',
        failVimoLink: 'Liên kết Vimo thất bại',
        successReOTPVimo: 'Mã OTP đã được gửi lại',
        failReOTPVimo: 'Không thể gửi lại mã OTP',
        successChangeMethod: 'Bạn đã chuyển liên kết thành công',
        failChangeMethod: 'Bạn không thể chuyển liên kết'
    },
    loginWithBiometry: {
        hello: '<e>Xin chào,</e>',
        description: '<n><i>Chào mừng bạn quay trở lại với</i><g1> TienNgay.vn Đầu tư & Tích luỹ </g1><i> hãy đăng nhập nào</i></n>',
        loginWithOther: 'Đăng nhập với tài khoản khác'
    },
    biometry: {
        useFingerprint: 'Đăng nhập bằng vân tay của bạn',
        useFingerPrintError: 'Vân tay không khớp, vui lòng thử lại.',
        useFingerPrintManyTimesError:
            'Bạn đã nhập sai quá nhiều lần, vui lòng nhập mã pin.'
    }


};
export default Languages;
